name: Email Test

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #1. Clone
    - uses: actions/checkout@v4

    #2. AWS CLI 로그인 하기
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ap-northeast-2

      # 3. AWS CLI로 이메일 보내기
    - name: Send Email with SES
      run: |
        aws ses send-email \
          --from "mincoding@naver.com"\
          --destination "ToAddresses=sejin.choi@mincoding.co.kr" \
          --message 'Subject={Data="테스트 메일 전송",Charset=UTF-8},Body={Text={Data="제 래포...",Charset=UTF-8},Html={Data="<p>살려주세요 짤</p><img src=\"https://d2u3dcdbebyaiu.cloudfront.net/uploads/atch_img/592/3562402c7f1dbdfe0f71e8efaec1c981.jpeg\" alt=\"KFC 이미지\" style=\"max-width:100%;height:auto;\">",Charset=UTF-8}}'
  
    
